---
# Exercise for setting up a web server in an EC
- name: Remote control using ansible  
  # Use the public IP if the VM is already created
  hosts: 34.201.65.28
  # For Ubuntu instances, the user will be `ubuntu`
  # For Amazon LInux 2 instance, the user will be `ec2-user`
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup

