version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
     docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

#  configure_infrastructure: 
#    docker:
#      - image: cimg/python:3.10
#    steps:
#      - checkout
#      - add_ssh_keys:
#              # You can get this ID in the section where you registered the SSH Key
#              fingerprints: ["86:e1:0e:bb:9e:5b:2a:04:f6:3c:3a:16:5f:09:8f:50"]
#      - run:
#          name: Install Ansible
#          command: |
#            python -m pip install ansible
#      - run:
#          name: Run Playbook and Configure server
#          command: |
#            ansible-playbook -i inventory main-remote.yml


# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure

